name = "FluxSegmentationModels"
uuid = "1605cb43-1f43-4e2a-927f-88bb65a1907f"
authors = ["Joshua Billson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
